name: CombatLogEvo
main: com.AWDev.CombatLogEvo.CombatLogEvo
version: 1.0
api-version: 1.15
commands:
    cle:
        description: Provides the version of the plugin
        aliases: combatlogevo
        usage: /cle
permissions: